--Create database
CREATE DATABASE PublishingHouse;
GO

--Connect to created database
USE PublishingHouse;
GO

--Create tables
CREATE TABLE Genre (
	GenreID INT IDENTITY (1, 1) PRIMARY KEY,
	GenreName VARCHAR (25) NOT NULL
);

CREATE TABLE Author (
	AuthorID INT IDENTITY (1, 1) PRIMARY KEY,
	FirstName VARCHAR (100) NOT NULL,
	LastName VARCHAR (100) NOT NULL,
	Phone VARCHAR (50),
	Email VARCHAR (255) NOT NULL UNIQUE,
	BirthDate DATE, 
	Address VARCHAR (255),
	City VARCHAR (50),
	Country VARCHAR (50)
);

CREATE TABLE Publisher (
	PublisherID INT IDENTITY (1, 1) PRIMARY KEY,
	PublisherName VARCHAR (100) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Address VARCHAR (255),
	City VARCHAR (50),
	Country VARCHAR (50)
);

CREATE TABLE Editor (
	EditorID INT IDENTITY (1, 1) PRIMARY KEY,
	FirstName VARCHAR (100) NOT NULL,
	LastName VARCHAR (100) NOT NULL,
	Phone VARCHAR (50),
	Email VARCHAR (255) NOT NULL UNIQUE,
	BirthDate DATE, 
	Address VARCHAR (255),
	City VARCHAR (50),
	Country VARCHAR (50),
	ReportsTo INT, 
	FOREIGN KEY (ReportsTo) REFERENCES Editor (EditorID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE Store (
	StoreID INT IDENTITY (1, 1) PRIMARY KEY,
	StoreName VARCHAR (100) NOT NULL,
	Email VARCHAR (255) NOT NULL UNIQUE,
	Address VARCHAR (255),
	City VARCHAR (50),
	Country VARCHAR (50)
);

CREATE TABLE Book (
	BookID INT IDENTITY (1, 1) PRIMARY KEY,
	Title VARCHAR (100) NOT NULL,
	ListPrice DECIMAL(10, 2) NOT NULL,
	Edition INT NOT NULL,
	DatePublished DATE,
	GenreID INT NOT NULL,
	AuthorID INT NOT NULL,
	PublisherID INT NOT NULL,
	EditorID INT NOT NULL, 
	FOREIGN KEY (GenreID) REFERENCES Genre (GenreID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (AuthorID) REFERENCES Author (AuthorID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (PublisherID) REFERENCES Publisher (PublisherID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (EditorID) REFERENCES Editor (EditorID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Stocks (
	BookID INT,
	StoreID INT,
	Quantity INT,
	PRIMARY KEY (BookID, StoreID),
	FOREIGN KEY (BookID) REFERENCES Book (BookID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (StoreID) REFERENCES Store (StoreID) ON DELETE CASCADE ON UPDATE CASCADE
);




